version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: calorietracker-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${CAL_DB_NAME}
      - POSTGRES_USER=${CAL_DB_USER}
      - POSTGRES_PASSWORD=${CAL_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CAL_DB_USER} -d ${CAL_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: calorietracker-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/login"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8081
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  logstash:
    build:
      context: .
      dockerfile: Dockerfile.logstash
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
      - postgres
    environment:
      - CAL_DB_HOST=postgres
      - CAL_DB_PORT=5432
      - CAL_DB_NAME=${CAL_DB_NAME}
      - CAL_DB_USER=${CAL_DB_USER}
      - CAL_DB_PASSWORD=${CAL_DB_PASSWORD}
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    networks:
      - app-network

  elasticvue:
    image: cars10/elasticvue:1.7.0
    container_name: elasticvue
    ports:
      - "8081:8080"
    depends_on:
      - elasticsearch
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: calorietracker-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  elasticsearch_data:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app-network:
    driver: bridge
